<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Verifikasi Tiket | JemberGo</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="{{ asset('css/jembergo-fallback.css') }}" rel="stylesheet"></head>
<body class="bg-light"><nav class="navbar bg-white border-bottom"><div class="container"><a href="{{ route('dashboard') }}" class="navbar-brand"><span class="brand-wordmark">Jember<span class="brand-accent">Go</span></span></a><a href="{{ route('dashboard') }}" class="text-dark text-decoration-none">Dashboard</a></div></nav>
<main class="container py-5"><div class="row justify-content-center"><div class="col-xl-10"><span class="text-warning text-uppercase small fw-bold">Operasional destinasi</span><h1 class="display-6 fw-bold mt-2">Verifikasi tiket</h1><p class="text-secondary">Masukkan kode booking untuk melihat seluruh data pemesanan sebelum memverifikasi tiket.</p>
@if(session('verification_success'))<div class="alert alert-success">{{ session('verification_success') }}</div>@endif
@if(session('verification_error'))<div class="alert alert-danger">{{ session('verification_error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm rounded-4 mt-4"><div class="card-body p-4 p-lg-5"><form method="POST" action="{{ route('admin.verification.lookup') }}">@csrf<label for="kode_booking" class="form-label">Kode tiket QR atau kode booking</label><div class="input-group"><input id="kode_booking" name="kode_booking" value="{{ old('kode_booking') }}" class="form-control form-control-lg" placeholder="Scan/tempel kode tiket atau JGO-20260901-A8271" required><button class="btn btn-warning px-4" type="submit">Cari tiket</button></div></form>
@if(isset($booking))<hr class="my-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2"><div><span class="badge text-bg-success">{{ \App\Support\StatusLabel::payment($booking->pembayaran->status_pembayaran) }}</span><h2 class="h4 fw-bold mt-2 mb-1">{{ $booking->kode_booking }}</h2><small class="text-secondary">Dipesan {{ $booking->tanggal_pemesanan->format('d/m/Y H:i') }}</small></div><div class="text-md-end"><span class="badge text-bg-warning">Kunjungan {{ $booking->tanggal_kunjungan->format('d/m/Y') }}</span><div class="small text-secondary mt-2">Status pemesanan: <strong>{{ \App\Support\StatusLabel::order($booking->status_pemesanan) }}</strong></div></div></div>
<div class="row g-3 mt-2"><div class="col-md-6"><div class="bg-light rounded-3 p-3 h-100"><small class="text-secondary d-block">Data pemesan</small><strong>{{ $booking->ketua_nama }}</strong><div class="small text-secondary">{{ $booking->ketua_email }}</div><div class="small text-secondary">{{ $booking->ketua_no_hp }}</div><hr><small class="text-secondary d-block">Customer</small><strong>{{ $booking->customer->nama ?? '-' }}</strong><div class="small text-secondary">{{ $booking->customer->email ?? '-' }}</div></div></div><div class="col-md-6"><div class="bg-light rounded-3 p-3 h-100"><small class="text-secondary d-block">Destinasi</small><strong>{{ $booking->destinasi->nama_wisata }}</strong><div class="small text-secondary">{{ $booking->destinasi->alamat }}</div><hr><div class="d-flex justify-content-between"><span>Total pembayaran</span><strong>Rp {{ number_format($booking->total_harga, 0, ',', '.') }}</strong></div><div class="small text-secondary">Metode: {{ $booking->pembayaran->metode_pembayaran ?? '-' }} · Ref: {{ $booking->pembayaran->referensi_gateway ?? '-' }}</div></div></div></div>
<h3 class="h6 fw-bold mt-4">Rincian pesanan</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Jenis tiket</th><th>Jumlah</th><th>Subtotal</th></tr></thead><tbody>@foreach($booking->detailPemesanan as $detail)<tr><td>{{ $detail->jenisTiket->nama_jenis ?? '-' }}</td><td>{{ $detail->jumlah }}</td><td>Rp {{ number_format($detail->subtotal, 0, ',', '.') }}</td></tr>@endforeach</tbody></table></div>
<h3 class="h6 fw-bold mt-4">Peserta dan status tiket</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>Nama peserta</th><th>Kode tiket</th><th>Status</th><th>Verifikasi</th></tr></thead><tbody>@foreach($booking->tiket as $index => $ticket)<tr class="{{ $selectedTicketId === $ticket->id_tiket ? 'table-warning' : '' }}"><td>{{ $index + 1 }}</td><td>{{ $index === 0 ? $booking->ketua_nama : data_get($booking->anggota_names, ($index - 1).'.nama', 'Anggota '.($index + 1)) }}</td><td class="text-break">{{ $ticket->kode_qr }}</td><td><span class="badge {{ $ticket->status_tiket === 'ACTIVE' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ \App\Support\StatusLabel::ticket($ticket->status_tiket) }}</span></td><td>{{ $ticket->waktu_verifikasi?->format('d/m/Y H:i') ?? '-' }}</td></tr>@endforeach</tbody></table></div>
<form method="POST" action="{{ route('admin.verification.verify') }}" onsubmit="return confirm('{{ $selectedTicketId ? 'Verifikasi tiket yang dipindai?' : 'Verifikasi seluruh tiket aktif pada booking ini?' }}')">@csrf<input type="hidden" name="id_pemesanan" value="{{ $booking->id_pemesanan }}">@if($selectedTicketId)<input type="hidden" name="id_tiket" value="{{ $selectedTicketId }}">@endif<button class="btn btn-success rounded-pill w-100" type="submit">{{ $selectedTicketId ? 'Verifikasi tiket ini dan tandai sudah digunakan' : 'Verifikasi semua tiket aktif menjadi sudah digunakan' }}</button></form>@endif</div></div></div></div></main></body></html>
