<x-admin-layout title="Verifikasi Tiket" active="verification">
    <div class="mb-4"><span class="text-warning text-uppercase small fw-bold">Operasional destinasi</span><h1 class="display-6 fw-bold mt-2">Verifikasi tiket</h1><p class="text-secondary">Masukkan kode booking atau scan QR untuk melihat data kelompok dan memverifikasi tiket.</p></div>
    @if(session('verification_success'))<div class="alert alert-success">{{ session('verification_success') }}</div>@endif
    @if(session('verification_error'))<div class="alert alert-danger">{{ session('verification_error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4 p-lg-5">
        <form method="POST" action="{{ route('admin.verification.lookup') }}">@csrf<label for="kode_booking" class="form-label">Kode booking atau QR grup</label><div class="input-group"><input id="kode_booking" name="kode_booking" value="{{ old('kode_booking') }}" class="form-control form-control-lg" placeholder="Masukkan kode booking atau scan QR grup" required><button class="btn btn-warning px-4" type="submit">Tampilkan data</button></div></form>
        @if(isset($booking))
            @php($participants = collect($booking->anggota_names ?? [])->prepend(['nama' => $booking->ketua_nama, 'id_jenis_tiket' => (int) $booking->ketua_jenis_tiket])->values())
            <hr class="my-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><span class="badge {{ $booking->pembayaran->status_pembayaran === 'PAID' ? 'text-bg-success' : 'text-bg-warning' }}">{{ \App\Support\StatusLabel::payment($booking->pembayaran->status_pembayaran) }}</span><h2 class="h4 fw-bold mt-2 mb-1">{{ $booking->kode_booking }}</h2><small class="text-secondary">Ketua: {{ $booking->ketua_nama }} · {{ $booking->ketua_email }} · {{ $booking->ketua_no_hp }}</small></div><div class="text-md-end"><span class="badge text-bg-warning">Kunjungan {{ $booking->tanggal_kunjungan->format('d/m/Y') }}</span><div class="small text-secondary mt-2">{{ $booking->destinasi->nama_wisata }} · {{ $participants->count() }} peserta · Rp {{ number_format($booking->total_harga, 0, ',', '.') }}</div></div></div>
            <div class="bg-light rounded-3 p-3 mt-4"><strong class="d-block mb-2">Anggota kelompok</strong>@forelse($participants->skip(1) as $member)<span class="badge bg-white text-dark border me-2 mb-2">{{ $member['nama'] }} · {{ $booking->detailPemesanan->firstWhere('id_jenis_tiket', (int) $member['id_jenis_tiket'])?->jenisTiket?->nama_jenis ?? 'Tiket' }}</span>@empty<span class="small text-secondary">Tidak ada anggota tambahan.</span>@endforelse</div>
            <h3 class="h6 fw-bold mt-4">Peserta, jenis tiket, dan status</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Peserta</th><th>Jenis tiket</th><th>Kode booking</th><th>Status</th><th>Waktu verifikasi</th></tr></thead><tbody>@foreach($booking->tiket as $index => $ticket)@php($participant = $participants->get($index, ['nama' => $booking->ketua_nama, 'id_jenis_tiket' => (int) $booking->ketua_jenis_tiket]))<tr class="{{ $selectedTicketId === $ticket->id_tiket ? 'table-warning' : '' }}"><td><strong>{{ $participant['nama'] }}</strong>@if($index === 0)<small class="d-block text-secondary">Ketua kelompok</small>@endif</td><td>{{ $booking->detailPemesanan->firstWhere('id_jenis_tiket', (int) $participant['id_jenis_tiket'])?->jenisTiket?->nama_jenis ?? 'Tiket' }}</td><td class="font-monospace">{{ $booking->kode_booking }}</td><td><span class="badge {{ $ticket->status_tiket === 'ACTIVE' ? 'text-bg-primary' : 'text-bg-secondary' }}">{{ \App\Support\StatusLabel::ticket($ticket->status_tiket) }}</span></td><td>{{ $ticket->waktu_verifikasi?->setTimezone(config('app.timezone'))->format('d/m/Y H:i') ?? '-' }}</td></tr>@endforeach</tbody></table></div>
            <form method="POST" action="{{ route('admin.verification.verify') }}" onsubmit="return confirm('Verifikasi seluruh tiket aktif pada booking ini?')">@csrf<input type="hidden" name="id_pemesanan" value="{{ $booking->id_pemesanan }}"><button class="btn btn-success rounded-pill w-100" type="submit">Verifikasi seluruh tiket aktif</button></form>
        @endif
    </div></div>
</x-admin-layout>