<x-admin-layout title="Verifikasi Tiket" active="verification">
    <div class="mb-4"><span class="text-warning text-uppercase small fw-bold">Operasional destinasi</span><h1 class="display-6 fw-bold mt-2">Verifikasi tiket</h1><p class="text-secondary">Masukkan kode booking atau scan QR untuk melihat data dan mengubah status tiket.</p></div>
    @if(session('verification_success'))<div class="alert alert-success">{{ session('verification_success') }}</div>@endif
    @if(session('verification_error'))<div class="alert alert-danger">{{ session('verification_error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4 p-lg-5">
        <form method="POST" action="{{ route('admin.verification.lookup') }}">@csrf<label for="kode_booking" class="form-label">Kode booking atau hasil scan QR</label><div class="input-group"><input id="kode_booking" name="kode_booking" value="{{ old('kode_booking') }}" class="form-control form-control-lg" placeholder="JGO-20260901-A8271" required><button class="btn btn-warning px-4" type="submit">Cari tiket</button></div></form>
        @if(isset($booking))
            <hr class="my-4"><div class="d-flex flex-wrap justify-content-between gap-2"><div><span class="badge text-bg-success">{{ $booking->pembayaran->status_pembayaran }}</span><h2 class="h4 fw-bold mt-2 mb-1">{{ $booking->kode_booking }}</h2><small class="text-secondary">{{ $booking->ketua_nama }} · {{ $booking->ketua_email }} · {{ $booking->ketua_no_hp }}</small></div><div class="text-md-end"><span class="badge text-bg-warning">Kunjungan {{ $booking->tanggal_kunjungan->format('d/m/Y') }}</span><div class="small text-secondary mt-2">{{ $booking->destinasi->nama_wisata }} · Rp {{ number_format($booking->total_harga, 0, ',', '.') }}</div></div></div>
            <h3 class="h6 fw-bold mt-4">Peserta dan status tiket</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Peserta</th><th>Kode booking</th><th>Status</th><th>Waktu verifikasi</th></tr></thead><tbody>@foreach($booking->tiket as $index => $ticket)<tr class="{{ $selectedTicketId === $ticket->id_tiket ? 'table-warning' : '' }}"><td>{{ $index === 0 ? $booking->ketua_nama : data_get($booking->anggota_names, ($index - 1).'.nama', 'Anggota '.($index + 1)) }}</td><td>{{ $booking->kode_booking }}</td><td><span class="badge {{ $ticket->status_tiket === 'ACTIVE' ? 'text-bg-primary' : 'text-bg-secondary' }}">{{ $ticket->status_tiket }}</span></td><td>{{ $ticket->waktu_verifikasi?->setTimezone(config('app.timezone'))->format('d/m/Y H:i') ?? '-' }}</td></tr>@endforeach</tbody></table></div>
            <form method="POST" action="{{ route('admin.verification.verify') }}" onsubmit="return confirm('{{ $selectedTicketId ? 'Verifikasi tiket yang dipindai?' : 'Verifikasi seluruh tiket aktif pada booking ini?' }}')">@csrf<input type="hidden" name="id_pemesanan" value="{{ $booking->id_pemesanan }}">@if($selectedTicketId)<input type="hidden" name="id_tiket" value="{{ $selectedTicketId }}">@endif<button class="btn btn-success rounded-pill w-100" type="submit">{{ $selectedTicketId ? 'Verifikasi tiket ini' : 'Verifikasi semua tiket aktif' }}</button></form>
+        @endif
+    </div></div>
+</x-admin-layout>