<x-admin-layout title="Riwayat & Laporan" active="history">
    <div class="admin-dashboard-shell">
        <div class="admin-dashboard-heading">
            <div><span class="admin-kicker">Operasional destinasi</span><h1>Riwayat & laporan tiket</h1><p>Satu baris menampilkan satu booking dan seluruh tiket yang sudah diverifikasi.</p></div>
            <a href="{{ route('admin.verification') }}" class="btn btn-warning">Verifikasi tiket <i class="bi bi-arrow-right ms-1" aria-hidden="true"></i></a>
        </div>
        <div class="admin-stat-grid">
            <article class="admin-stat-card"><div class="admin-stat-icon admin-stat-icon-green"><i class="bi bi-patch-check" aria-hidden="true"></i></div><span>Tiket terverifikasi</span><strong>{{ number_format($report['tickets']) }}</strong><small>Status: Sudah digunakan</small></article>
            <article class="admin-stat-card"><div class="admin-stat-icon"><i class="bi bi-calendar-check" aria-hidden="true"></i></div><span>Booking terverifikasi</span><strong>{{ number_format($report['bookings']) }}</strong><small>Booking unik</small></article>
            <article class="admin-stat-card"><div class="admin-stat-icon admin-stat-icon-blue"><i class="bi bi-wallet2" aria-hidden="true"></i></div><span>Total pendapatan</span><strong>Rp {{ number_format($report['revenue'], 0, ',', '.') }}</strong><small>Dari booking terverifikasi</small></article>
        </div>
        <section class="admin-panel admin-bookings-panel"><div class="admin-panel-heading"><div><span class="admin-kicker">Aktivitas selesai</span><h2>Riwayat verifikasi</h2><p>Detail tiket yang sudah diverifikasi pada destinasi Anda.</p></div></div><div class="table-responsive"><table class="table admin-bookings-table align-middle mb-0"><thead><tr><th>Booking & pemesan</th><th>Ketua dan anggota</th><th>Peserta terverifikasi</th><th>Destinasi</th><th class="text-end">Pendapatan</th></tr></thead><tbody>@forelse($bookings as $booking)<tr><td><strong>{{ $booking->kode_booking }}</strong><small>{{ $booking->customer->nama ?? '-' }}</small><small>{{ $booking->tanggal_kunjungan->format('d/m/Y') }}</small></td><td><strong>{{ $booking->ketua_nama }}</strong><small>Ketua</small>@foreach($booking->anggota_names ?? [] as $member)<small>{{ data_get($member, 'nama', $member) }} · Anggota</small>@endforeach</td><td>@foreach($booking->tiket as $ticketIndex => $ticket)@php($participantName = $ticketIndex === 0 ? $booking->ketua_nama : data_get($booking->anggota_names, ($ticketIndex - 1).'.nama', 'Anggota '.($ticketIndex + 1)))<div class="admin-status-text mb-1">{{ $participantName }} · Sudah digunakan</div><small>{{ $ticket->waktu_verifikasi?->setTimezone(config('app.timezone'))->format('d/m/Y H:i') ?? '-' }}</small>@endforeach</td><td>{{ $booking->destinasi->nama_wisata }}</td><td class="text-end text-nowrap">Rp {{ number_format($booking->total_harga, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5"><div class="admin-empty"><i class="bi bi-calendar2-x" aria-hidden="true"></i><strong>Belum ada tiket terverifikasi</strong><span>Riwayat verifikasi akan muncul di sini.</span></div></td></tr>@endforelse</tbody></table></div></section>
        <div class="mt-4">{{ $bookings->links() }}</div>
    </div>
</x-admin-layout>
